name: tests

on:
  push:
    branches: [ "main", "dev", "ci" ]
  pull_request:
    branches: [ "main", "dev" ]

# designed as in: https://github.com/marketplace/actions/setup-miniconda
jobs:
  build:
    name: build nf env
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: nextflow
          environment-file: env/conda_nxf.yml
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          auto-activate-base: false

      - name: Test conda installation
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Test nextflow installation
        run: |
          nextflow -version


  run-hap:
    name: Run hap.nf
    needs: build
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: nextflow
          environment-file: env/conda_nxf.yml
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          auto-activate-base: false

      - name : Download reference
        run: |
          wget https://www.ebi.ac.uk/ena/browser/api/fasta/MN908947.3
          sed 's/>ENA|MN908947|MN908947.3 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome./>MN908947.3/g' MN908947.3 > MN908947.3.fasta
          mkdir -p reference/Sars-Cov-2/Wuhan-Hu-1/
          mv MN908947.3.fasta reference/Sars-Cov-2/Wuhan-Hu-1/
      
      - name: Test haplotype simulation
        run: |
          nextflow run hap.nf -profile local,conda

  run-eval:
    name: Run eval.nf
    needs: build
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: nextflow
          environment-file: env/conda_nxf.yml
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          auto-activate-base: false

      - name : Download reference
        run: |
          wget https://www.ebi.ac.uk/ena/browser/api/fasta/MN908947.3
          sed 's/>ENA|MN908947|MN908947.3 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome./>MN908947.3/g' MN908947.3 > MN908947.3.fasta
          mkdir -p reference/Sars-Cov-2/Wuhan-Hu-1/
          mv MN908947.3.fasta reference/Sars-Cov-2/Wuhan-Hu-1/

      - name: Test callset evaluation with callset_dir
        run: |
          nextflow run eval.nf -profile local,conda --callsets_dir aux/ci_data/

      - name: Test callset evaluation with sample_sheet
        run: |
          echo "index,callset,truthset" > my_samples.csv
          echo "1,aux/ci_data/callset_1.vcf.gz,results/simulated_hap1.vcf" >> my_samples.csv
          echo "2,aux/ci_data/callset_2.vcf.gz,results/simulated_hap2.vcf" >> my_samples.csv
          echo "3,aux/ci_data/callset_3.vcf.gz,results/simulated_hap3.vcf" >> my_samples.csv
          
          nextflow run eval.nf -profile local,conda --sample_sheet my_samples.csv

